spring.application.name=ecommerce
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce_user
spring.datasource.password=ecommerce_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=your_super_secret_key_must_be_at_least_32_characters
app.jwt.expiration-ms=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Report config
app.report.recipient=recipient@example.com
app.report.schedule.transactions=0 0 8 * * MON
app.report.schedule.bestsellers=0 0 18 * * SUN

server.port=8080
