spring.application.name=ecommerce
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:ecommerce;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH:/h2-console}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false
# spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.mail.enabled=${MANAGEMENT_HEALTH_MAIL_ENABLED:false}
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.enable.tomcat=true
management.endpoint.metrics.enabled=true

# JWT
app.jwt.secret=${APP_JWT_SECRET:your_super_secret_key_must_be_at_least_32_characters}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

# Mail
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:yousefalshikhali1711@gmail.com}
spring.mail.password=uozy ejoe vexd ykgm
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

# Report config
app.report.recipient=${APP_REPORT_RECIPIENT:recipient@example.com}
app.report.schedule.transactions=${APP_REPORT_SCHEDULE_TRANSACTIONS:0 0 8 * * MON}
app.report.schedule.bestsellers=${APP_REPORT_SCHEDULE_BESTSELLERS:0 0 18 * * SUN}

server.port=${SERVER_PORT:8080}
server.tomcat.mbeanregistry.enabled=true

# Resource Management
server.tomcat.threads.max=100
server.tomcat.accept-count=200
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=3000
app.capacity.max-concurrent-requests=60
app.capacity.max-wait-ms=200
app.async.core-pool-size=4
app.async.max-pool-size=8
app.async.queue-capacity=200

# RabbitMQ 
spring.rabbitmq.host=192.168.1.6
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=pass


app.batch.schedule=0 0 0 * * ?




