global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: spring-cluster
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app1:8080
          - app2:8080
        labels:
          environment: docker-cluster

  - job_name: spring-local
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          environment: local-host
