spring.application.name=ecommerce
# قاعدة بيانات H2 (ذاكرة مؤقتة، لا تحتاج تثبيت)
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# لوحة تحكم H2 (تظهر على المتصفح لتستعرض البيانات)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA: يقوم بإنشاء الجداول تلقائياً
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# المنفذ الافتراضي (تأكد أنه 8080)
server.port=8080